# Generated by Django 4.2.6 on 2023-10-23 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('area_tag', models.CharField(blank=True, max_length=255)),
                ('topic_tag', models.CharField(blank=True, max_length=255)),
                ('link', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('source_tag', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('additional_info', models.CharField(blank=True, max_length=255)),
                ('type_of_threat', models.CharField(blank=True, max_length=255)),
                ('evaluation', models.CharField(blank=True, max_length=255)),
                ('grand_narrative', models.CharField(blank=True, max_length=255)),
                ('narrative', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('suggestions_for_response', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('ua_region', models.CharField(blank=True, max_length=255)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
